/*
 * PoliceAboutBox.java
 */

package Harvester;

import java.awt.Desktop;
import org.jdesktop.application.Action;

public class PoliceAboutBox extends javax.swing.JDialog {

    public PoliceAboutBox(java.awt.Frame parent, Desktop desktop) {
        super(parent);
        this.desktop = desktop;
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    @Action public void closeAboutBox() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
        javax.swing.JLabel versionLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
        javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
        authorsLabel = new javax.swing.JLabel();
        nicholasDunn = new javax.swing.JLabel();
        jeremyFishman = new javax.swing.JLabel();
        tuckerHermans = new javax.swing.JLabel();
        homepageLink = new javax.swing.JLabel();
        versionNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Harvester.PoliceApp.class).getContext().getResourceMap(PoliceAboutBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Harvester.PoliceApp.class).getContext().getActionMap(PoliceAboutBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        appTitleLabel.setText(resourceMap.getString("appTitleLabel.text")); // NOI18N
        appTitleLabel.setName("appTitleLabel"); // NOI18N

        versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
        versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
        versionLabel.setName("versionLabel"); // NOI18N

        appVersionLabel.setName("appVersionLabel"); // NOI18N

        homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
        homepageLabel.setText(resourceMap.getString("homepageLabel.text")); // NOI18N
        homepageLabel.setName("homepageLabel"); // NOI18N

        appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
        appDescLabel.setName("appDescLabel"); // NOI18N

        authorsLabel.setFont(resourceMap.getFont("authorsLabel.font")); // NOI18N
        authorsLabel.setText(resourceMap.getString("authorsLabel.text")); // NOI18N
        authorsLabel.setName("authorsLabel"); // NOI18N

        nicholasDunn.setText(resourceMap.getString("nicholasDunn.text")); // NOI18N
        nicholasDunn.setToolTipText(resourceMap.getString("nicholasDunn.toolTipText")); // NOI18N
        nicholasDunn.setName("nicholasDunn"); // NOI18N

        jeremyFishman.setText(resourceMap.getString("jeremyFishman.text")); // NOI18N
        jeremyFishman.setToolTipText(resourceMap.getString("jeremyFishman.toolTipText")); // NOI18N
        jeremyFishman.setName("jeremyFishman"); // NOI18N

        tuckerHermans.setText(resourceMap.getString("tuckerHermans.text")); // NOI18N
        tuckerHermans.setToolTipText(resourceMap.getString("tuckerHermans.toolTipText")); // NOI18N
        tuckerHermans.setName("tuckerHermans"); // NOI18N

        homepageLink.setText(resourceMap.getString("homepageLink.text")); // NOI18N
        homepageLink.setToolTipText(resourceMap.getString("homepageLink.toolTipText")); // NOI18N
        homepageLink.setName("homepageLink"); // NOI18N

        versionNumber.setText(resourceMap.getString("versionNumber.text")); // NOI18N
        versionNumber.setName("versionNumber"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(appTitleLabel)
                            .add(appDescLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(versionLabel)
                                    .add(authorsLabel)
                                    .add(homepageLabel))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(nicholasDunn)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jeremyFishman, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, tuckerHermans, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .add(homepageLink)
                                    .add(versionNumber))
                                .add(203, 203, 203))
                            .add(layout.createSequentialGroup()
                                .add(118, 118, 118)
                                .add(appVersionLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 384, Short.MAX_VALUE)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(closeButton)
                        .add(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(appTitleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(appDescLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(versionLabel)
                    .add(appVersionLabel)
                    .add(versionNumber))
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(authorsLabel)
                    .add(nicholasDunn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tuckerHermans)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jeremyFishman)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(homepageLabel)
                    .add(homepageLink))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nicholasDunn.addMouseListener(new HyperlinkListener(desktop, "mailto:ndunn2@bowdoin.edu"));
        jeremyFishman.addMouseListener(new HyperlinkListener(desktop, "mailto:jfishman@bowdoin.edu"));
        tuckerHermans.addMouseListener(new HyperlinkListener(desktop, "mailto:thermans@bowdoin.edu"));
        homepageLink.addMouseListener(new HyperlinkListener(desktop, "http://robocup.bowdoin.edu"));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel homepageLink;
    private javax.swing.JLabel jeremyFishman;
    private javax.swing.JLabel nicholasDunn;
    private javax.swing.JLabel tuckerHermans;
    private javax.swing.JLabel versionNumber;
    // End of variables declaration//GEN-END:variables
    private Desktop desktop;
}
